fix: types

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,38 +1,46 @@
 #!/bin/bash
 
-remote="$1"
-url="$2"
+# Name of the docker image
+#image_name="<dockerhub-name>/template"
 
-z40=0000000000000000000000000000000000000000
+# Run tests (if any)
+# poetry run pytest
 
-while read local_ref local_sha remote_ref remote_sha
-do
-    if [ "$local_sha" = $z40 ]
-    then
-        # Handle delete
-        :
-    else
-        if [ "$remote_sha" = $z40 ]
-        then
-            # New branch, examine all commits
-            range="$local_sha"
-        else
-            # Update to existing branch, examine new commits
-            range="$remote_sha..$local_sha"
-        fi
+# Run cz bump with poetry
+poetry run cz bump --yes
 
-        # Check for changes in "devcontainers/" directory
-        commit=$(git diff --name-only "$range" | grep "^devcontainers/")
+# If cz bump fails, unstash changes and exit with an error code
+if [ $? -ne 0 ]; then
+  echo "cz bump failed, cancelling commit"
+  git stash pop -q
+  exit $?
+fi
 
-        if [ -n "$commit" ]; then
-            # We have changes in "devcontainers/" directory
-            for dir in $(git diff --name-only "$range" | grep "^devcontainers/" | cut -d/ -f2 | uniq); do
-                echo "Changes found in devcontainers/$dir..."
-                docker build -t recrash/$dir:latest devcontainers/$dir
-                docker push recrash/$dir:latest
-            done
-        fi
-    fi
-done
+# Add changes to the commit if the version was bumped
+if git diff --name-only | grep -q 'VERSION\|pyproject.toml'; then
+  echo "Version has been bumped, adding changes to the commit..."
+  git add -u :/
+  git commit --amend --no-edit
+fi
 
-exit 0
+# Check if image_name variable is set
+if [ -n "$image_name" ]; then
+  # Dockerfile location
+  dockerfile_path=".devcontainer/Dockerfile"
+
+  # Building docker image
+  echo "Building Docker image from Dockerfile at $dockerfile_path..."
+  # Uncomment below line to enable docker build
+  # docker build -t $image_name -f $dockerfile_path .
+
+  # Pushing to Docker Hub
+  echo "Pushing Docker image to Docker Hub..."
+  # Uncomment below line to enable docker push
+  # docker push $image_name
+
+  # If Docker build or push fail, stop the push
+  if [ $? -ne 0 ]; then
+    echo "Docker build or push failed, cancelling git push"
+    exit 1
+  fi
+fi
